// Master catalog of all single-player metropolis sandboxes. Pure data, no DOM/three.js.
// Organized into 7 Regional Acts + Prologue across 29 world metropolises.
// Single source of truth for narrative lore, hero landmarks, progression gating, and coin economies.
//
// KNOWN OPEN ISSUE — tools/validate-campaign.mjs is RED against this file.
// That suite sorts the roster ascending by `blocks` and asserts coinCount,
// coinValue and goalBonus are each non-decreasing along it, i.e. it treats map
// size as a proxy for campaign progression. Correcting the two wrong declared
// counts on 2026-08-19 (gallery 13652 -> 15767, cambridge 88500 -> 72943)
// falsifies that proxy in five places:
//
//   sydney(70 coins)    -> gallery(60)     gallery is the PROLOGUE tutorial and
//                                          is meant to be the poorest reward on
//                                          the board; its size grew because
//                                          ADR-0022 added a camera testbed, not
//                                          because it became a bigger LEVEL.
//   cambridge(200/5/500) -> upper-manhattan(120/3/150)
//                                          cambridge is the ACT VII finale with a
//                                          deliberately huge endgame economy, but
//                                          at its true 72,943 it is only the 3rd
//                                          largest map, behind tokyo (ACT II).
//
// The suite was green before the correction ONLY because the two wrong numbers
// happened to place gallery smallest and cambridge largest. The fiction was
// load-bearing for the gate. Verified by re-running the suite against a clean
// `git archive HEAD` tree: ALL PASS there, 5 breaks here.
//
// Deliberately NOT resolved here, because every available fix is someone else's
// call: changing any coinCount/coinValue/goalBonus is a game-balance decision,
// and changing the suite's sort key is shaping a gate to pass. Sorting by act
// then catalog order is strictly worse (14 breaks), which confirms the block
// sort really is that suite's intended premise rather than an accident.
// Escalated to the campaign owner. Do not "fix" this by editing the two block
// counts back — they are the accurate ones and are gated by validate.mjs's
// declaredBlockCounts section.

export const CITY_CATALOG = [
  // --- PROLOGUE: CALIBRATION ---
  {
    scene: 'gallery',
    name: 'THE LAB',
    location: 'PROVING GROUND',
    act: 'PROLOGUE',
    actTitle: 'CALIBRATION',
    sub: 'Physics playground & training yard',
    desc: 'The spark begins. Compact starter grid with ramps, street props, and calibration structures.',
    tagline: 'PROLOGUE · CALIBRATION',
    chapter: 'PROLOGUE',
    status: 'PLAYABLE',
    // 13652 -> 15767: ADR-0022 authored a permanent 3-tower camera testbed into
    // The Lab and nobody moved this number. The Lab is a testbed, so the
    // GEOMETRY is the intended thing here and this number was the stale side —
    // the opposite of Sydney, where the declared count was authoritative
    // because it is a city map the owner specified.
    blocks: 15767,
    difficulty: 'TIER 1 · STARTER',
    badge: 'PROLOGUE',
    accentColor: '#00f0ff',
    icon: '🧪',
    coinCount: 60,
    coinValue: 1,
    goalBonus: 25,
    heroes: ['Crash Ramps', 'Calibration Pylons', 'Subway Terminal'],
    momentumFriend: 'Clockwork Moth 🦋',
    directive: 'CALIBRATE VORTEX & INGEST STARTER SNACKS',
    transmission: 'Initial boot sequence complete. Kinetic void online. Consume low-mass testing props to calibrate rotational inertia and establish baseline momentum.',
    debrief: 'Calibration phase 100% complete. Frictionless core verified. Ready for global deployment.',
  },

  // --- ACT I: THE PACIFIC AWAKENING ---
  {
    scene: 'sydney',
    name: 'SYDNEY HARBOUR',
    location: 'SYDNEY, AUSTRALIA',
    act: 'ACT I',
    actTitle: 'THE PACIFIC AWAKENING',
    sub: 'Opera House, Harbour Bridge & Circular Quay',
    desc: 'Sprocket goes global. Soaring ceramic sail vaults, deep water bays, and the iconic Coathanger bridge.',
    tagline: 'CHAPTER 1 · HARBOUR VOYAGE',
    chapter: 'CHAPTER 1',
    status: 'PLAYABLE',
    blocks: 14120,
    difficulty: 'TIER 2 · CASUAL',
    badge: 'ACT I',
    accentColor: '#4cc9f0',
    icon: '🦘',
    coinCount: 70,
    coinValue: 1,
    goalBonus: 50,
    heroes: ['Opera House Sail Vaults', 'Harbour Bridge Arch', 'Sydney Tower Eye'],
    momentumFriend: 'Sydney Seagull Bot 🕊️',
    directive: 'CALIBRATE OCEANIC INERTIA & CONSUME THE SAIL VAULTS',
    transmission: 'Target: Port Jackson. Ingest coastal bollards and ferries to build sufficient angular velocity for the Harbour Bridge through-arch.',
    debrief: 'Sydney sector 100% converted. Oceanic resonance achieved. Vector locked for trans-Pacific leap.',
  },
  {
    scene: 'auckland',
    name: 'AUCKLAND',
    location: 'NEW ZEALAND',
    act: 'ACT I',
    actTitle: 'THE PACIFIC AWAKENING',
    sub: 'Sky Tower, Waitematā Ferries & Volcanic Cones',
    desc: 'Harbour city nestled among volcanic hills. Towering needle spires, maritime wharves, and steep coastlines.',
    tagline: 'CHAPTER 2 · PACIFIC REACH',
    chapter: 'CHAPTER 2',
    status: 'PLAYABLE',
    blocks: 16000,
    difficulty: 'TIER 2 · CASUAL',
    badge: 'ACT I',
    accentColor: '#48cae4',
    icon: '⛵',
    coinCount: 72,
    coinValue: 1,
    goalBonus: 55,
    heroes: ['Sky Tower Needle', 'Waitematā Ferry Wharves', 'Mt Eden Volcanic Cones'],
    momentumFriend: 'Kiwi Clockwork Bot 🥝',
    directive: 'OVERCOME SOUTHERN LATITUDES & DISSOLVE THE SKY TOWER',
    transmission: 'Approaching Hauraki Gulf. Coastal thermal drafts detected. Ingest ferry terminals before taking down the 300m needle spire.',
    debrief: 'Auckland sector cleared. Southern hemisphere flywheel harmonics stabilized.',
  },
  {
    scene: 'singapore',
    name: 'SINGAPORE MARINA BAY',
    location: 'SINGAPORE',
    act: 'ACT I',
    actTitle: 'THE PACIFIC AWAKENING',
    sub: 'Marina Bay Sands, Supertrees & Merlion',
    desc: 'Garden megacity of futuristic cantilevers, towering biome domes, and luminous vertical gardens.',
    tagline: 'CHAPTER 3 · EQUATORIAL GARDEN',
    chapter: 'CHAPTER 3',
    status: 'DEVELOPMENT',
    blocks: 22000,
    difficulty: 'TIER 3 · NORMAL',
    badge: 'ACT I',
    accentColor: '#00b4d8',
    icon: '🦁',
    coinCount: 75,
    coinValue: 2,
    goalBonus: 60,
    heroes: ['Marina Bay Sands SkyPark', 'Supertree Grove', 'Merlion Waterfront'],
    momentumFriend: 'Merlion Cub Bot 🦁',
    directive: 'INGEST BOTANICAL SUPERSTRUCTURES & CRUMBLE SKYPARK',
    transmission: 'Equatorial sector entered. High humidity and dense vertical geometry. Sweep the waterfront promenades before attacking the tripartite hotel towers.',
    debrief: 'Marina Bay sector absorbed. Bio-kinetic momentum compounded.',
  },

  // --- ACT II: ASIAN MEGACITIES & HIGH-DENSITY GRIDS ---
  {
    scene: 'hongkong',
    name: 'HONG KONG',
    location: 'VICTORIA HARBOUR',
    act: 'ACT II',
    actTitle: 'ASIAN MEGACITIES',
    sub: 'Victoria Peak, Bank Towers & Star Ferries',
    desc: 'Vertical island archipelago of hyper-dense skyscraper canyons, inclined peak trams, and double-decker trams.',
    tagline: 'CHAPTER 4 · VERTICAL ISLAND',
    chapter: 'CHAPTER 4',
    status: 'DEVELOPMENT',
    blocks: 28500,
    difficulty: 'TIER 3 · NORMAL',
    badge: 'ACT II',
    accentColor: '#ff5d8f',
    icon: '🚢',
    coinCount: 86,
    coinValue: 2,
    goalBonus: 85,
    heroes: ['Bank of China Tower', 'Peak Tramway', 'Star Ferry Docks'],
    momentumFriend: 'Junk Boat Bot ⛵',
    directive: 'NAVIGATE CANYON SHEAR & TOPPLE FINANCIAL TOWERS',
    transmission: 'Entering Victoria Harbour. Dense maritime and urban layering. Use narrow streets to chain combos across double-decker transit grids.',
    debrief: 'Hong Kong skyline converted into kinetic energy. Momentum curve rising exponentially.',
  },
  {
    scene: 'seoul',
    name: 'SEOUL',
    location: 'SOUTH KOREA',
    act: 'ACT II',
    actTitle: 'ASIAN MEGACITIES',
    sub: 'N Seoul Tower, Han River Bridges & Ancient Gates',
    desc: 'Techno-capital blending futuristic high-rises, historic palace gates, and wide river spanning bridges.',
    tagline: 'CHAPTER 5 · TECHNO HARMONY',
    chapter: 'CHAPTER 5',
    status: 'DEVELOPMENT',
    blocks: 32000,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT II',
    accentColor: '#ff758f',
    icon: '🏯',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 95,
    heroes: ['N Seoul Tower', 'Han River Crossings', 'Gyeongbokgung Gate'],
    momentumFriend: 'Magpie Drone Bot 🐦',
    directive: 'CROSS THE HAN RIVER & HARMONIZE PALACE PAVILIONS',
    transmission: 'Seoul sector reached. Balance ancient wooden temple structures with high-frequency tech towers. Maximize combo chains along the riverside boulevards.',
    debrief: 'Seoul sector fully captured. Harmonic balance achieved.',
  },
  {
    scene: 'tokyo',
    name: 'TOKYO SHINJUKU',
    location: 'TOKYO, JAPAN',
    act: 'ACT II',
    actTitle: 'ASIAN MEGACITIES',
    sub: 'Neo-Shinjuku Skyscraper Grid & Shibuya Scramble',
    desc: 'Mega metropolis with dazzling neon, endless towers, and bustling scramble crossings.',
    tagline: 'CHAPTER 6 · MEGA METROPOLIS',
    chapter: 'CHAPTER 6',
    status: 'PLAYABLE',
    blocks: 84122,
    difficulty: 'TIER 8 · APEX',
    badge: 'ACT II',
    accentColor: '#ff0054',
    icon: '🗼',
    coinCount: 160,
    coinValue: 4,
    goalBonus: 300,
    heroes: ['Shibuya Scramble Crossing', 'Tokyo Red Tower', 'Shinjuku Neon Canyons'],
    momentumFriend: 'Tanuki Gear Bot 🦝',
    directive: 'NAVIGATE 84,000 NEON VOXELS & ENGULF THE MEGAPLEX',
    transmission: 'Tokyo apex sector reached. Vast voxel density exceeding 84k blocks. Build massive rim speed across Shibuya scramble before challenging the monolith towers.',
    debrief: 'Tokyo mega-grid 100% ingested! Singular kinetic output achieved.',
  },
  {
    scene: 'beijing',
    name: 'BEIJING',
    location: 'CHINA',
    act: 'ACT II',
    actTitle: 'ASIAN MEGACITIES',
    sub: "Forbidden Gates, Bird's Nest & CCTV Loop",
    desc: 'Monumental imperial avenues, colossal steel structural loops, and ancient courtyard hutongs.',
    tagline: 'CHAPTER 7 · IMPERIAL AXIS',
    chapter: 'CHAPTER 7',
    status: 'DEVELOPMENT',
    blocks: 38000,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT II',
    accentColor: '#d90429',
    icon: '🐉',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ["Bird's Nest Steel Lattice", 'CCTV Cantilever Loop', 'Imperial Palace Gates'],
    momentumFriend: 'Imperial Lion Bot 🐲',
    directive: 'PENETRATE IMPERIAL AXIS & UNRAVEL CANTILEVER LOOPS',
    transmission: 'Imperial central sector. Large architectural scale requires careful foundation undermining. Detach external lattice bracing.',
    debrief: 'Beijing central axis converted. High structural integrity conquered.',
  },
  {
    scene: 'bangkok',
    name: 'BANGKOK',
    location: 'THAILAND',
    act: 'ACT II',
    actTitle: 'ASIAN MEGACITIES',
    sub: 'Wat Arun Spire, River Barges & Floating Markets',
    desc: 'Lively canal networks, intricate temple spires, bustling night markets, and elevated skytrains.',
    tagline: 'CHAPTER 8 · RIVER OF KINGS',
    chapter: 'CHAPTER 8',
    status: 'DEVELOPMENT',
    blocks: 30000,
    difficulty: 'TIER 3 · NORMAL',
    badge: 'ACT II',
    accentColor: '#ffb703',
    icon: '🛺',
    coinCount: 88,
    coinValue: 2,
    goalBonus: 90,
    heroes: ['Wat Arun Spire', 'Chao Phraya Barges', 'Tuk-Tuk Night Market'],
    momentumFriend: 'Tuk-Tuk Bot 🛺',
    directive: 'NAVIGATE CANAL WATERWAYS & INGEST TEMPLE MOSAICS',
    transmission: 'Canal sector active. High density of mobile market stalls and ornate porcelain spires. Clear the riverbanks to unlock higher tiers.',
    debrief: 'Bangkok waterways cleared. Kinetic resonance fully restored.',
  },
  {
    scene: 'mumbai',
    name: 'MUMBAI',
    location: 'INDIA',
    act: 'ACT II',
    actTitle: 'ASIAN MEGACITIES',
    sub: 'Gateway of India, Marine Drive & Victoria Terminus',
    desc: 'Historic Victorian Gothic monoliths along the Arabian Sea, bustling coastal drives, and rail hubs.',
    tagline: 'CHAPTER 9 · ARABIAN HORIZON',
    chapter: 'CHAPTER 9',
    status: 'DEVELOPMENT',
    blocks: 34500,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT II',
    accentColor: '#fb8500',
    icon: '🚂',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Gateway of India Arch', 'Marine Drive Coastline', 'Victoria Terminus Clocktower'],
    momentumFriend: 'Chai Kettle Bot 🫖',
    directive: 'DEVOUR GOTHIC TERMINALS & SWEEP MARINE DRIVE',
    transmission: 'Approaching the coastal terminus. High density of commuters and ornate sandstone arches. Ingest street carts before confronting the Grand Terminus.',
    debrief: 'Mumbai sector 100% converted. Arabian Sea corridor cleared.',
  },

  // --- ACT III: DESERT HORIZONS & MEDITERRANEAN ANTIQUITY ---
  {
    scene: 'dubai',
    name: 'DUBAI',
    location: 'UNITED ARAB EMIRATES',
    act: 'ACT III',
    actTitle: 'DESERT & ANTIQUITY',
    sub: 'Burj Pinnacle, Palm Monorail & Sail Hotel',
    desc: 'Ultra-modern oasis rising from desert dunes, soaring spires, artificial archipelagos, and luxury supertalls.',
    tagline: 'CHAPTER 10 · DESERT PINNACLE',
    chapter: 'CHAPTER 10',
    status: 'DEVELOPMENT',
    blocks: 36000,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT III',
    accentColor: '#e0aaff',
    icon: '🏜️',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Burj Khalifa Needle', 'Palm Monorail Trestle', 'Sail Hotel Tower'],
    momentumFriend: 'Falcon Sky Bot 🦅',
    directive: 'CONQUER SUPERTALL HEIGHTS & ENGULF PALM BRIDGES',
    transmission: 'Desert thermal conditions. Extreme elevation gradient. Consume low-lying monorail pylons to build sufficient mass for the supertall needle.',
    debrief: 'Dubai sector ingested. Kinetic momentum defying gravity.',
  },
  {
    scene: 'cairo',
    name: 'CAIRO & GIZA',
    location: 'EGYPT',
    act: 'ACT III',
    actTitle: 'DESERT & ANTIQUITY',
    sub: 'Giza Limestone Pyramids, Nile Feluccas & Citadel',
    desc: 'Ancient stone monoliths, historic Nile riverbanks, limestone tombs, and medieval fortress walls.',
    tagline: 'CHAPTER 11 · SANDS OF TIME',
    chapter: 'CHAPTER 11',
    status: 'DEVELOPMENT',
    blocks: 32500,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT III',
    accentColor: '#c77dff',
    icon: '🐪',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 95,
    heroes: ['Giza Limestone Pyramids', 'Nile Felucca Wharves', 'Citadel Fortress Towers'],
    momentumFriend: 'Scarab Gear Bot 🪲',
    directive: 'CRUMBLE LIMESTONE COLOSSI & CONVERT ANCIENT MASS',
    transmission: 'Ancient sector detected. Dense solid stone composition requires extreme mass tolerance. Undermine pyramid corbels block by block.',
    debrief: 'Cairo stone monuments digitized and preserved in Pocket Workshop.',
  },
  {
    scene: 'athens',
    name: 'ATHENS',
    location: 'GREECE',
    act: 'ACT III',
    actTitle: 'DESERT & ANTIQUITY',
    sub: 'Acropolis Parthenon, Plaka Stairs & Port Piraeus',
    desc: 'Cradle of classical geometry. Pentelic marble colonnades, hillside stairs, and olive groves.',
    tagline: 'CHAPTER 12 · MARBLE COLONNADE',
    chapter: 'CHAPTER 12',
    status: 'DEVELOPMENT',
    blocks: 26000,
    difficulty: 'TIER 3 · NORMAL',
    badge: 'ACT III',
    accentColor: '#9d4edd',
    icon: '🏛️',
    coinCount: 82,
    coinValue: 2,
    goalBonus: 75,
    heroes: ['Acropolis Parthenon', 'Plaka Stepped Streets', 'Erechtheion Caryatids'],
    momentumFriend: 'Owl of Athena Bot 🦉',
    directive: 'DISMANTLE CLASSICAL COLONNADES & CAPTURE THE ACROPOLIS',
    transmission: 'Entering the sacred rock. Doric and Ionic marble pillars are highly brittle to rotational shear. Strike the foundation plinths.',
    debrief: 'Athens sector cleared. Classical harmonic proportions unlocked.',
  },
  {
    scene: 'rome',
    name: 'ROME',
    location: 'ITALY',
    act: 'ACT III',
    actTitle: 'DESERT & ANTIQUITY',
    sub: 'Colosseum Oval, St. Peter’s Dome & Trevi Fountains',
    desc: 'Eternal city of ancient travertine amphitheatres, Renaissance domes, cobblestone plazas, and aqueducts.',
    tagline: 'CHAPTER 13 · ETERNAL ARCHES',
    chapter: 'CHAPTER 13',
    status: 'DEVELOPMENT',
    blocks: 35000,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT III',
    accentColor: '#7b2cbf',
    icon: '🏺',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Colosseum Oval Arena', 'St. Peter’s Great Dome', 'Roman Aqueduct Arches'],
    momentumFriend: 'Vespa Scooter Bot 🛵',
    directive: 'COLLAPSE TRAVERTINE ARCADES & ENGULF THE COLOSSEUM',
    transmission: 'Target: Imperial Rome. Massive Roman concrete and travertine vaults. Use combo multipliers to sweep the piazza fountains first.',
    debrief: 'Rome sector absorbed. Ancient engineering converted into perpetual drive.',
  },

  // --- ACT IV: EUROPEAN CAPITALS OF GRANDEUR ---
  {
    scene: 'paris',
    name: 'PARIS',
    location: 'FRANCE',
    act: 'ACT IV',
    actTitle: 'EUROPEAN GRANDEUR',
    sub: 'Eiffel Tower, Arc de Triomphe & Seine Bridges',
    desc: 'Haussmannian boulevards, intricate iron lattice towers, grand triumphal monuments, and stone riverbanks.',
    tagline: 'CHAPTER 14 · CITY OF LIGHT',
    chapter: 'CHAPTER 14',
    status: 'DEVELOPMENT',
    blocks: 42000,
    difficulty: 'TIER 5 · EXPERT',
    badge: 'ACT IV',
    accentColor: '#5a189a',
    icon: '🥐',
    coinCount: 98,
    coinValue: 2,
    goalBonus: 120,
    heroes: ['Eiffel Tower Iron Lattice', 'Arc de Triomphe Corbel', 'Pont Neuf Stone Bridge'],
    momentumFriend: 'Croissant Bot 🥐',
    directive: 'DISASSEMBLE WROUGHT IRON LATTICE & SWEEP THE SEINE',
    transmission: 'Approaching the Champ de Mars. 300m wrought-iron lattice requires multi-point structural undermining. Ingest cafe kiosks on the avenue first.',
    debrief: 'Paris sector fully revived. Kinetic flywheel spinning in perfect resonance.',
  },
  {
    scene: 'london',
    name: 'LONDON',
    location: 'UNITED KINGDOM',
    act: 'ACT IV',
    actTitle: 'EUROPEAN GRANDEUR',
    sub: 'Big Ben, Tower Bridge, The Shard & London Eye',
    desc: 'Historic Thames waterway, iconic bascule suspension towers, neo-Gothic clocktowers, and glass pyramids.',
    tagline: 'CHAPTER 15 · THAMES CROSSING',
    chapter: 'CHAPTER 15',
    status: 'DEVELOPMENT',
    blocks: 45000,
    difficulty: 'TIER 5 · EXPERT',
    badge: 'ACT IV',
    accentColor: '#3c096c',
    icon: '💂',
    coinCount: 105,
    coinValue: 2,
    goalBonus: 130,
    heroes: ['Big Ben Clocktower', 'Tower Bridge Bascules', 'The Shard Spire'],
    momentumFriend: 'Double-Decker Bus Bot 🚌',
    directive: 'SYNCHRONIZE BIG BEN CHIMES & CONSUME TOWER BRIDGE',
    transmission: 'Foggy Thames corridor. Heavy red telephone boxes, routemasters, and dual-leaf bascule bridge piers. Undermine river towers to collapse the span.',
    debrief: 'London clockwork mechanisms restarted. Great bells chiming once more.',
  },
  {
    scene: 'amsterdam',
    name: 'AMSTERDAM',
    location: 'NETHERLANDS',
    act: 'ACT IV',
    actTitle: 'EUROPEAN GRANDEUR',
    sub: 'Canal Rings, Step-Gable Houses & Windmills',
    desc: 'Concentric brick canal rings, arched bridges, narrow canal merchant houses, and picturesque windmills.',
    tagline: 'CHAPTER 16 · CANAL RINGS',
    chapter: 'CHAPTER 16',
    status: 'DEVELOPMENT',
    blocks: 28000,
    difficulty: 'TIER 3 · NORMAL',
    badge: 'ACT IV',
    accentColor: '#240046',
    icon: '🚲',
    coinCount: 85,
    coinValue: 2,
    goalBonus: 80,
    heroes: ['Canal Ring Bridge Network', 'Step-Gable Merchant Mansions', 'Historic Windmill Blades'],
    momentumFriend: 'Windmill Gear Bot 🚲',
    directive: 'CHAIN COMBOS ACROSS CANALS & ENGULF THE GABLES',
    transmission: 'Entering the Grachtengordel. Narrow canal quays offer prime combo chains. Ingest parked bicycles and barges before tackling the brick rows.',
    debrief: 'Amsterdam canals revived. Windmills turning smoothly across the horizon.',
  },
  {
    scene: 'berlin',
    name: 'BERLIN',
    location: 'GERMANY',
    act: 'ACT IV',
    actTitle: 'EUROPEAN GRANDEUR',
    sub: 'Brandenburg Gate, Fernsehturm TV Tower & Spree',
    desc: 'Monumental neoclassical sandstone gates, towering retro-futuristic spheres, and modern cultural plazas.',
    tagline: 'CHAPTER 17 · CONTINENTAL CROSSING',
    chapter: 'CHAPTER 17',
    status: 'DEVELOPMENT',
    blocks: 36500,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT IV',
    accentColor: '#10002b',
    icon: '🐻',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Brandenburg Gate Sandstone Arch', 'Fernsehturm TV Sphere', 'Reichstag Glass Dome'],
    momentumFriend: 'Berlin Bear Bot 🐻',
    directive: 'TOPPLE SANDSTONE COLONNADES & CONSUME THE TV TOWER',
    transmission: 'Target: Alexanderplatz and Pariser Platz. Sandstone colonnades and high TV tower pylon. Strike corner columns to initiate domino collapse.',
    debrief: 'Berlin sector cleared. Trans-Atlantic trajectory locked.',
  },

  // --- ACT V: THE AMERICAS & TRANSCONTINENTAL TRANSIT ---
  {
    scene: 'rio',
    name: 'RIO DE JANEIRO',
    location: 'BRAZIL',
    act: 'ACT V',
    actTitle: 'THE AMERICAS',
    sub: 'Sugarloaf Cableway, Corcovado Peak & Copacabana',
    desc: 'Dramatic tropical granite peaks, sweeping oceanfront boulevards, cable car networks, and seaside mosaic pavements.',
    tagline: 'CHAPTER 18 · TROPICAL PEAKS',
    chapter: 'CHAPTER 18',
    status: 'DEVELOPMENT',
    blocks: 38500,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT V',
    accentColor: '#52b788',
    icon: '🌴',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Sugarloaf Mountain Cable Cars', 'Corcovado Monument Peak', 'Copacabana Wave Mosaics'],
    momentumFriend: 'Toucan Bot 🦜',
    directive: 'SCALE GRANITE MONOLITHS & ENGULF TROPICAL PROMENADES',
    transmission: 'South American arrival. Dramatic vertical topography. Follow the wave-patterned sidewalks to build mass before scaling the mountain crests.',
    debrief: 'Rio de Janeiro coastline energized. Samba rhythm flywheel spinning.',
  },
  {
    scene: 'buenosaires',
    name: 'BUENOS AIRES',
    location: 'ARGENTINA',
    act: 'ACT V',
    actTitle: 'THE AMERICAS',
    sub: 'Avenida 9 de Julio, Obelisco & La Boca',
    desc: 'Massive multi-lane avenues, iconic obelisk monuments, vibrant corrugated zinc lofts, and historic tango plazas.',
    tagline: 'CHAPTER 19 · AVENUE OF HEROES',
    chapter: 'CHAPTER 19',
    status: 'DEVELOPMENT',
    blocks: 34000,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT V',
    accentColor: '#74c69d',
    icon: '💃',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Obelisco National Plaza', 'Avenida 9 de Julio Boulevards', 'La Boca Corrugated Lofts'],
    momentumFriend: 'Bandoneón Tango Bot 🪗',
    directive: 'SWEEP THE WORLD’S WIDEST AVENUE & CRUMBLE THE OBELISK',
    transmission: 'Entering 16-lane avenue grid. Wide open road spans allow rapid sweeping. Build high velocity along the median to tackle the 67m Obelisco.',
    debrief: 'Buenos Aires sector 100% captured. Kinetic tango momentum compounding.',
  },
  {
    scene: 'mexicocity',
    name: 'MEXICO CITY',
    location: 'MEXICO',
    act: 'ACT V',
    actTitle: 'THE AMERICAS',
    sub: 'Angel of Independence, Zócalo & Reforma',
    desc: 'High-altitude metropolis with grand monumental roundabouts, historic cathedral plazas, and modern Reforma towers.',
    tagline: 'CHAPTER 20 · VALLEY OF SUN',
    chapter: 'CHAPTER 20',
    status: 'DEVELOPMENT',
    blocks: 37000,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT V',
    accentColor: '#95d5b2',
    icon: '🌮',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['Angel of Independence Column', 'Zócalo Metropolitan Cathedral', 'Paseo de la Reforma Towers'],
    momentumFriend: 'Axolotl Gear Bot 🦎',
    directive: 'ENGULF MONUMENTAL ROUNDABOUTS & ZÓCALO CANYONS',
    transmission: 'Valley of Mexico sector. Rich historical layers over volcanic lakebeds. Circle the roundabouts to clear prop clusters before taking the central columns.',
    debrief: 'Mexico City sector clear. Trans-continental vector locked northward.',
  },
  {
    scene: 'sanfrancisco',
    name: 'SAN FRANCISCO',
    location: 'CALIFORNIA',
    act: 'ACT V',
    actTitle: 'THE AMERICAS',
    sub: 'Golden Gate Bridge, Cable Cars & Transamerica',
    desc: 'Steep hill slopes, iconic suspension spans, Victorian Painted Ladies, and historic cable car turnarounds.',
    tagline: 'CHAPTER 21 · PACIFIC BAY',
    chapter: 'CHAPTER 21',
    status: 'DEVELOPMENT',
    blocks: 44000,
    difficulty: 'TIER 5 · EXPERT',
    badge: 'ACT V',
    accentColor: '#e76f51',
    icon: '🌁',
    coinCount: 100,
    coinValue: 2,
    goalBonus: 125,
    heroes: ['Golden Gate Suspension Bridge', 'Cable Car Hill Climbers', 'Transamerica Pyramid Tower'],
    momentumFriend: 'Cable Car Bell Bot 🌁',
    directive: 'MASTER STEEP GRADE PHYSICS & INGEST GOLDEN GATE',
    transmission: 'Bay Area grid entered. Steep elevation shifts test angular steering control. Ride downhill avenues to build massive momentum toward the bridge towers.',
    debrief: 'San Francisco Bay sector 100% converted. Golden Gate kinetic revival achieved.',
  },
  {
    scene: 'chicago',
    name: 'CHICAGO LOOP',
    location: 'CHICAGO, IL',
    act: 'ACT V',
    actTitle: 'THE AMERICAS',
    sub: 'The Loop, Willis Tower & Iconic River Crossings',
    desc: 'Colossal skyscraper grid, elevated rail loops with runaway CTA train physics, and deep river ravines.',
    tagline: 'CHAPTER 22 · SKYSCRAPER CANYONS',
    chapter: 'CHAPTER 22',
    status: 'PLAYABLE',
    blocks: 44578,
    difficulty: 'TIER 5 · EXPERT',
    badge: 'ACT V',
    accentColor: '#ff2a2a',
    icon: '🌆',
    coinCount: 100,
    coinValue: 2,
    goalBonus: 125,
    heroes: ['Willis Tower Monolith', 'Elevated CTA Runaway Train Loop', 'Chicago River Bascule Bridges'],
    momentumFriend: 'Loop Train Bot 🚂',
    directive: 'INTERCEPT CTA RUNAWAY TRAINS & COLLAPSE WILLIS TOWER',
    transmission: 'Windy City sector. High-velocity elevated trains looping overhead. Undermine the rail trestle stanchions to bring down the runaway trains!',
    debrief: 'Chicago Loop converted. High-torque railway momentum absorbed into flywheel core.',
  },
  {
    scene: 'toronto',
    name: 'TORONTO',
    location: 'CANADA',
    act: 'ACT V',
    actTitle: 'THE AMERICAS',
    sub: 'CN Tower Pod, Rogers Dome & Waterfront',
    desc: 'Lake Ontario metropolis featuring freestanding broadcast towers, retractable stadium domes, and red streetcar corridors.',
    tagline: 'CHAPTER 23 · NORTHERN SHORES',
    chapter: 'CHAPTER 23',
    status: 'DEVELOPMENT',
    blocks: 40000,
    difficulty: 'TIER 5 · EXPERT',
    badge: 'ACT V',
    accentColor: '#f4a261',
    icon: '🍁',
    coinCount: 95,
    coinValue: 2,
    goalBonus: 110,
    heroes: ['CN Tower SkyPod', 'Rogers Centre Retractable Dome', 'King Street Transit Line'],
    momentumFriend: 'Beaver Solder Bot 🦫',
    directive: 'OVERCOME BROADCAST SPIRES & DISSOLVE STADIUM DOMES',
    transmission: 'Approaching Lake Ontario waterfront. High broadcast tower requires deep foundation shearing. Clear streetcars and waterfront docks first.',
    debrief: 'Toronto sector cleared. All Canadian kinetic systems back in motion.',
  },

  // --- ACT VI: THE NEW YORK MEGACITY TRILOGY ---
  {
    scene: 'manhattan',
    name: 'LOWER MANHATTAN',
    location: 'NEW YORK CITY',
    act: 'ACT VI',
    actTitle: 'NEW YORK TRILOGY',
    sub: 'Financial District, Wall Street & Downtown Skyscrapers',
    desc: 'Dense skyscraper canyon grid with granite plazas, historic churches, and monolith towers.',
    tagline: 'CHAPTER 24 · FINANCIAL GRID',
    chapter: 'CHAPTER 24',
    status: 'PLAYABLE',
    blocks: 25875,
    difficulty: 'TIER 3 · NORMAL',
    badge: 'ACT VI',
    accentColor: '#ffd23f',
    icon: '🏙️',
    coinCount: 80,
    coinValue: 2,
    goalBonus: 75,
    heroes: ['Wall Street Financial Canyons', 'Trinity Historic Church', 'One World Monolith'],
    momentumFriend: 'Subway Rat Bot 🐀',
    directive: 'NAVIGATE WALL STREET CANYONS & TOPPLE FINANCIAL TOWERS',
    transmission: 'Entering New York megacity sector. Deep granite corridors and high-rise density. Consume hot dog stands and turnstiles to unlock the monoliths.',
    debrief: 'Lower Manhattan 100% swallowed. Wall Street momentum converted to infinite torque.',
  },
  {
    scene: 'brooklyn',
    name: 'BROOKLYN',
    location: 'NEW YORK CITY',
    act: 'ACT VI',
    actTitle: 'NEW YORK TRILOGY',
    sub: 'Bridges to Coney Island, DUMBO & East River Piers',
    desc: 'Sprawling waterfront with suspension bridges, ferry docks, coaster trestles, and warehouses.',
    tagline: 'CHAPTER 25 · WATERFRONT METROPOLIS',
    chapter: 'CHAPTER 25',
    status: 'PLAYABLE',
    blocks: 39984,
    difficulty: 'TIER 4 · SKILLED',
    badge: 'ACT VI',
    accentColor: '#ff9f1c',
    icon: '🌉',
    coinCount: 90,
    coinValue: 2,
    goalBonus: 100,
    heroes: ['DUMBO Industrial Lofts', 'Brooklyn Suspension Bridge', 'Coney Island Coaster Trestle'],
    momentumFriend: 'Waterfront Crane Bot 🏗️',
    directive: 'UNDERMINE DUMBO LOFTS & CONSUME THE SUSPENSION BRIDGE',
    transmission: 'East River sector active. Sweeping suspension spans and industrial warehouse masonry. Break through pier bollards to reach the bridge anchorage.',
    debrief: 'Brooklyn waterfront ingested. East River bridges and docks humming with kinetic life.',
  },
  {
    scene: 'upper-manhattan',
    name: 'UPPER MANHATTAN',
    location: 'NEW YORK CITY',
    act: 'ACT VI',
    actTitle: 'NEW YORK TRILOGY',
    sub: 'Central Park perimeter & Historic Brownstones',
    desc: 'Vast parkland surrounded by classic avenues, grand museums, and Victorian brownstone rows.',
    tagline: 'CHAPTER 26 · PARKLAND & UPTOWN',
    chapter: 'CHAPTER 26',
    status: 'PLAYABLE',
    blocks: 73393,
    difficulty: 'TIER 6 · MASTER',
    badge: 'ACT VI',
    accentColor: '#06d6a0',
    icon: '🌳',
    coinCount: 120,
    coinValue: 3,
    goalBonus: 150,
    heroes: ['Central Park Perimeter Parkland', 'Metropolitan Grand Museum', 'Victorian Brownstone Blocks'],
    momentumFriend: 'Central Park Squirrel Bot 🐿️',
    directive: 'SWEEP CENTRAL PARK PROMENADES & ENGULF 73,000 VOXELS',
    transmission: 'Central Park perimeter. 73,000+ blocks of lush parkland, grand stone museums, and classic brownstones. Scale up from park benches to museum colonnades.',
    debrief: 'Upper Manhattan 100% cleared! New York Trilogy complete.',
  },

  // --- ACT VII: THE MASSACHUSETTS TECH CORRIDOR & GRAND FINALE ---
  {
    scene: 'boston',
    name: 'BOSTON SEAPORT',
    location: 'MASSACHUSETTS',
    act: 'ACT VII',
    actTitle: 'TECH CORRIDOR & FINALE',
    sub: 'Seaport Boulevard, BCEC & Historic Harbor',
    desc: 'Massive convention halls, seaport piers, historic wharves, and high-density coastal blocks.',
    tagline: 'CHAPTER 27 · COASTAL EXPEDITION',
    chapter: 'CHAPTER 27',
    status: 'PLAYABLE',
    blocks: 82894,
    difficulty: 'TIER 7 · TITAN',
    badge: 'ACT VII',
    accentColor: '#3a86ff',
    icon: '⚓',
    coinCount: 140,
    coinValue: 3,
    goalBonus: 200,
    heroes: ['BCEC Convention Megastructure', 'Seaport Coastal Wharves', 'Boston Tea Party Pier'],
    momentumFriend: 'Beacon Hill Pigeon Bot 🕊️',
    directive: 'INGEST BCEC CONVENTION COMPLEX & STAGE FOR CAMBRIDGE',
    transmission: 'Staging in Boston Seaport. Colossal 82k block convention halls and deep seaport wharves. Prepare the flywheel core for the final crossing over the Charles River.',
    debrief: 'Boston Seaport devoured. All vector coordinates locked on Cambridge and Canal Park!',
  },
  {
    scene: 'cambridge',
    name: 'CAMBRIDGE',
    location: 'MASSACHUSETTS · HUBSPOT HQ',
    act: 'ACT VII',
    actTitle: 'TECH CORRIDOR & FINALE',
    sub: 'Kendall Square, Canal Park & The UNBOUND Summit',
    desc: 'The grand finale of Sprocket’s journey. Tech innovation district, brick mills, and HubSpot Global HQ at Canal Park.',
    tagline: 'GRAND FINALE · HUBSPOT HQ',
    chapter: 'FINALE',
    status: 'PLAYABLE',
    // 88500 -> 72943: 88,500 has never been true. Cambridge was specced to LOOK
    // as detailed as ~73k voxels and the number was read as a literal target
    // once already; the map has been 72,943 since it was built, and Cambridge 2
    // is deferred. The card now describes the map that exists rather than one
    // that was never authored.
    blocks: 72943,
    difficulty: 'TIER 9 · SUMMIT',
    badge: 'GRAND FINALE',
    accentColor: '#9d4edd',
    icon: '🚀',
    coinCount: 200,
    coinValue: 5,
    goalBonus: 500,
    heroes: ['2 Canal Park (HubSpot Global HQ)', 'First Street Garage Rooftop', 'The Great Flywheel Sprocket Mark'],
    momentumFriend: 'The Grand Flywheel Bot ⚙️',
    directive: 'SWALLOW THE SPROCKET AT 2 CANAL PARK & IGNITE UNBOUND',
    transmission: 'FINAL OBJECTIVE. Kendall Square and Canal Park. Ingest the tech campuses, ascend to the roof of the First Street Garage, and SWALLOW THE SPROCKET to unleash infinite global momentum!',
    debrief: 'THE SPROCKET HAS BEEN SWALLOWED! Infinite flywheel momentum unlocked. The world is moving again! Welcome to UNBOUND!',
  },
];

// Returns all 29 cities in their canonical story progression order
export function getSortedCityCatalog() {
  return [...CITY_CATALOG];
}

// Returns only the active playable sandbox cities
export function getPlayableCityCatalog() {
  return CITY_CATALOG.filter((c) => c.status === 'PLAYABLE');
}

// Progression Gate: A city is unlocked if it is the first in the ladder (The Lab / Sydney Harbour),
// or if the player has already played it and recorded a score/run on it.
// If not yet played, it unlocks when the nearest preceding PLAYABLE city has achieved
// a 100% full clear in under the 5-minute (300s) duration limit.
export function isCityUnlocked(save, cityScene, sortedCatalog) {
  const catalog = sortedCatalog || getSortedCityCatalog();
  const idx = catalog.findIndex((c) => c.scene === cityScene);
  if (cityScene === 'gallery' || cityScene === 'sydney') return true; // Starter cities always unlocked
  const currentRec = (save?.sandbox || {})[cityScene];
  if (currentRec && ((currentRec.runs || 0) > 0 || (currentRec.bestScore || 0) > 0 || (currentRec.completions || 0) > 0)) {
    return true;
  }
  if (idx <= 0) return false;

  // Find nearest preceding PLAYABLE city before this index
  let prevPlayable = null;
  for (let i = idx - 1; i >= 0; i--) {
    if (catalog[i].status === 'PLAYABLE') {
      prevPlayable = catalog[i];
      break;
    }
  }
  if (!prevPlayable) return true; // If no preceding playable city exists, unlocked by default

  const prevRec = (save?.sandbox || {})[prevPlayable.scene];
  if (!prevRec) return false;

  // Preceding playable city must have a 100% clear achieved within the 5-minute (300s) limit
  const hasFullClear = Boolean((prevRec.completions || 0) > 0 || (prevRec.bestPercent || 0) >= 1.0);
  const under5Minutes = prevRec.bestTime !== null && prevRec.bestTime !== undefined && prevRec.bestTime <= 300;
  return Boolean(hasFullClear && under5Minutes);
}

/** Check if the 3-minute challenge for a city is completed */
export function isCityChallengeCompleted(save, cityScene) {
  const ch = (save?.challenges || {})[cityScene];
  if (ch && ch.completed3m) return true;
  const sb = (save?.sandbox || {})[cityScene];
  // If sandbox recorded a clear in under 180s (3 minutes)
  if (sb && sb.bestTime != null && sb.bestTime <= 180 && ((sb.completions || 0) > 0 || (sb.bestPercent || 0) >= 1.0)) {
    return true;
  }
  return false;
}

/** Total number of 3-minute city challenges completed across playable cities */
export function getCompletedChallengeCount(save, sortedCatalog) {
  const catalog = (sortedCatalog || getPlayableCityCatalog()).filter((c) => c.status === 'PLAYABLE');
  let count = 0;
  for (const c of catalog) {
    if (isCityChallengeCompleted(save, c.scene)) {
      count++;
    }
  }
  return count;
}

/** Check if Secret 90s Challenge is unlocked (requires completing ALL playable 3m city challenges) */
export function isSecret90sChallengeUnlocked(save, sortedCatalog) {
  const catalog = (sortedCatalog || getPlayableCityCatalog()).filter((c) => c.status === 'PLAYABLE');
  if (catalog.length === 0) return false;
  return getCompletedChallengeCount(save, catalog) >= catalog.length;
}
