import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const {RenderBudget}=await import('../js/render-budget.js');
const b=new RenderBudget();
const feed=(dt,n)=>{for(let i=0;i<n;i++)b.sample(dt);};
feed(1/60,600);assert.equal(b.level,0,'stable 60 FPS retains detail');
feed(1/30,65);assert.equal(b.level,1,'sustained missed frames reduce rendering');
feed(1/30,130);assert.equal(b.level,3,'fallback is bounded');
const source={dpr:1.5,shadows:true,ambient:true,contactBudget:250};
assert.deepEqual(b.spec(source),{dpr:.75,shadows:false,ambient:false},'controller cannot return physics levers');
assert.equal(source.dpr,1.5,'settings are not mutated');
feed(1/60,120);assert.equal(b.level,3,'no oscillation after a short recovery');
feed(1/60,610);assert.equal(b.level,2,'sustained recovery restores one step');
b.sample(3);assert.equal(b.level,2,'background or loading gap is ignored');
b.reset();assert.equal(b.level,0);
feed(.3,7);assert.equal(b.level,1,'severely slow gameplay still triggers fallback');
const main=readFileSync(new URL('../js/main.js',import.meta.url),'utf8');
assert.match(main,/world\.setQuality\(renderBudget\.spec\(spec\)\)/,'only renderer receives adaptive spec');
assert.match(main,/renderBudget\.sample\(rawDt\)/);
console.log('ALL PASS render budget: bounded fallback, hysteresis, render-only policy');
